// Generated by CoffeeScript 1.7.1
(function() {
  var DroppedASSFile;

  document.ondrop = function() {
    return false;
  };

  document.ondragover = function() {
    return false;
  };

  DroppedASSFile = window.DroppedASSFile;

  Zepto(function($) {
    var cycleMessage, idList, live, messages, pushMessage, shiftMessage, start, suspendedAnimation;
    live = new Date;
    messages = $('#messages');
    start = 0;
    idList = [];
    suspendedAnimation = {};
    pushMessage = function(id, text) {
      idList.push(id);
      suspendedAnimation[id] = true;
      messages.append("<span id='" + id + "' class='message incoming'>" + text + "</span>");
      return $('#' + id).bind('oanimationend animationend webkitAnimationEnd MSAnimationEnd', function(ev) {
        ev.stopPropagation();
        return shiftMessage(id);
      });
    };
    shiftMessage = function(id) {
      var message;
      if (suspendedAnimation[id]) {
        return delete suspendedAnimation[id];
      } else {
        message = $('#' + id);
        message.removeClass('incoming');
        message.addClass('outgoing');
        return setTimeout(function() {
          return message.remove();
        }, 1000);
      }
    };
    cycleMessage = function(newMessage) {
      shiftMessage(idList.shift());
      return pushMessage((Math.floor(Math.random() * 1000000)).toString(16), newMessage);
    };
    pushMessage('message1', 'DROP A SCRIPT WITH MESSED UP EXTRADATA ON ME');
    document.getElementById('shield').ondrop = function(ev) {
      var file, _i, _len, _ref;
      _ref = ev.dataTransfer.files;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        new DroppedASSFile(file, cycleMessage, ++start, messages);
      }
      return false;
    };
    $('#body').on('dragenter', function(ev) {
      return $('#shield').show();
    });
    $('#shield').on('dragenter', function(ev) {
      return cycleMessage("DROP IT");
    });
    return $('#shield').on('dragleave', function(ev) {
      $('#shield').hide();
      return cycleMessage('DROP A SCRIPT WITH MESSED UP EXTRADATA ON ME');
    });
  });

}).call(this);
